name: Deploy Lambda

on:
  push:
    branches:
      - main
env:
  enviromentName: dev
jobs:
  deploy:
    name: Package and deploy to AWS
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Package code
        run: zip -r datalogger.zip package.json src/

      - name: Deploy Lambda code
        run: |
          aws lambda update-function-code \
            --function-name datalogger \
            --zip-file fileb://datalogger.zip
